pipeline {
    agent any

    stages {
		stage('Foundation') {
			// Build only if there are changes in the foundation definition.
			when { 
				anyOf {
					environment name: 'FORCE', value: 'true'
					changeset 'foundation/**'
				}
			} 
			steps {
			        build job: 'foundation', parameters: [string(name: 'BRANCH', value: params.BRANCH)]
			}
		}
		stage('Core') {
			steps {
		        build job: 'core', parameters: [string(name: 'RELEASE', value: params.BRANCH), string(name: 'BRANCH', value: params.BRANCH)]
			}
		}
		stage('HTML') {
			steps {
				build job: 'html', parameters: [string(name: 'RELEASE', value: params.BRANCH), string(name: 'BRANCH', value: params.BRANCH)]
			}
		}
		stage('Vinci') {
			steps {
				build job: 'vinci', parameters: [string(name: 'RELEASE', value: params.BRANCH), string(name: 'BRANCH', value: params.BRANCH)]
			}
		}
		stage('Codegen') {
			steps {
				build job: 'codegen', parameters: [string(name: 'RELEASE', value: params.BRANCH), string(name: 'BRANCH', value: params.BRANCH)]
			}
		}
//		stage('Rigel') {
//			steps {
//				build job: 'rigel', parameters: [string(name: 'RELEASE', value: params.BRANCH), string(name: 'BRANCH', value: params.BRANCH)]
//			}
//		}
		stage('Tool Suite') {
			steps {
			        build job: 'tool-suite', parameters: [string(name: 'BRANCH', value: params.BRANCH)]
			}
		}
    }
}
