pipeline {
    agent any

    stages {
		stage('Foundation') {
			// Build only if there are changes in the foundation definition.
			when { changeset "foundation/**"	} 
			steps {
			        build job: 'foundation', parameters: [string(name: 'BRANCH', value: params.BRANCH)]
			}
		    }
		stage('Core') {
			steps {
		        	build job: 'core', parameters: [string(name: 'RELEASE', value: params.BRANCH), string(name: 'BRANCH', value: params.BRANCH)]
			}
		}
		stage('HTML') {
			steps {
				build job: 'html', parameters: [string(name: 'RELEASE', value: params.BRANCH), string(name: 'BRANCH', value: params.BRANCH)]
			}
		}
		stage('Vinci') {
			steps {
				build job: 'vinci', parameters: [string(name: 'RELEASE', value: params.BRANCH), string(name: 'BRANCH', value: params.BRANCH)]
			}
		}
    }
}
