node {
    def branch = params.BRANCH
    stage('Foundation') {
        build job: 'foundation', parameters: [string(name: 'BRANCH', value: branch)]
    }
    stage('Core') {
        // Change the branch parameter if the core branch is different from the release branch.
        build job: 'core', parameters: [string(name: 'RELEASE', value: branch), string(name: 'BRANCH', value: branch)]
    }
}